# Generated by Django 4.1.6 on 2023-03-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Shopping', 'Shopping'), ('Travel', 'Travel'), ('Misc', 'Misc'), ('GenExpense', 'General Expense'), ('Education', 'Education')], default='Shopping', max_length=100)),
                ('description', models.TextField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'Mpesa'), ('Card', 'Card'), ('Cheque', 'Cheque')], default='Cash', max_length=20)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
