# Generated by Django 4.1.6 on 2023-03-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow_tracker', '0002_income_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(default='The goal is to put something on the table'),
            preserve_default=False,
        ),
    ]
