# Generated by Django 4.1.6 on 2023-03-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflow_tracker', '0003_income_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='payment_mode',
            new_name='payment',
        ),
    ]
